server:
  port: 0
  #context-path: /rest

security:
  oauth2:
    resource:
      token-info-uri: http://127.0.0.1:8081/oauth/check_token
    client:
      client-id: acme
      client-secret: acmesecret

---

spring:
  profiles: docker

security:
  oauth2:
    resource:
      token-info-uri: http://oauth-service:8081/oauth/check_token