server:
  context-path: /web
  port: 8080

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://127.0.0.1:8081/oauth/token
      user-authorization-uri: http://127.0.0.1:8081/oauth/authorize
      token-name: oauth_token
      authentication-scheme: header
zuul:
  routes:
    api:
      path: /api/**
      serviceId: edge-service
      # serviceId: resource-service
  debug:
    request: true

---

spring:
  profiles: docker

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://oauth-service:8081/oauth/token
      user-authorization-uri: http://127.0.0.1:8081/oauth/authorize
      token-name: oauth_token
      authentication-scheme: header